
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author harsh
 */
public class student_login extends javax.swing.JFrame {
public int abc;
public String ac;
    /**
     * Creates new form login
     */
    public student_login() {
        this.setUndecorated(true);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        usrtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdtxt = new javax.swing.JPasswordField();
        jLabellogin = new javax.swing.JLabel();
        jLabelcancel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        WTLMS = new javax.swing.JLabel();
        WTLMS1 = new javax.swing.JLabel();
        WTLMS2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1470, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 260, -1));

        usrtxt.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        usrtxt.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(usrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, 260, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        pwdtxt.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pwdtxt.setForeground(new java.awt.Color(0, 0, 204));
        pwdtxt.setEchoChar('*');
        getContentPane().add(pwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, 260, -1));

        jLabellogin.setBackground(new java.awt.Color(255, 153, 0));
        jLabellogin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabellogin.setForeground(new java.awt.Color(0, 0, 204));
        jLabellogin.setText("LOGIN");
        jLabellogin.setOpaque(true);
        jLabellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelloginMouseClicked(evt);
            }
        });
        getContentPane().add(jLabellogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, -1, -1));

        jLabelcancel.setBackground(new java.awt.Color(255, 153, 0));
        jLabelcancel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelcancel.setForeground(new java.awt.Color(0, 0, 204));
        jLabelcancel.setText("Don't have an account?");
        jLabelcancel.setOpaque(true);
        jLabelcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcancelMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 370, 40));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WTLMS.setBackground(new java.awt.Color(102, 0, 102));
        WTLMS.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        WTLMS.setForeground(new java.awt.Color(255, 255, 255));
        WTLMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/adminlogog.png"))); // NOI18N
        jPanel1.add(WTLMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 90, 680, 540));

        WTLMS1.setBackground(new java.awt.Color(255, 255, 255));
        WTLMS1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        WTLMS1.setForeground(new java.awt.Color(0, 0, 204));
        WTLMS1.setText("WELCOME TO LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(WTLMS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, 40));

        WTLMS2.setBackground(new java.awt.Color(255, 255, 255));
        WTLMS2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        WTLMS2.setForeground(new java.awt.Color(0, 0, 204));
        WTLMS2.setText("STUDENT LOGIN");
        jPanel1.add(WTLMS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 520, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 760));

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 60, 50));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/LMS_logo.PNG"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/eyep.PNG"))); // NOI18N
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 490, 50, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelloginMouseClicked
        String usr = usrtxt.getText();
        String pwd = new String(pwdtxt.getPassword());
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lib","root","abc");
            Statement stmt = con.createStatement();
            String query = " select * from student where uname = '"+usr+"' and pass = '"+pwd+"';";
            ResultSet rs = stmt.executeQuery(query);
            if(rs.next()) 
            {
                 abc = rs.getInt("sid");
                 ac = rs.getString("fname");
                JOptionPane.showMessageDialog(null,"Your USER ID  "+abc+"");
                userchoices o = new userchoices(abc,ac);
                o.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Username or password incorrect");
            }
        } 
        catch(Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabelloginMouseClicked

    private void jLabelcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcancelMouseClicked
        adminLogin obj = new adminLogin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelcancelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
      
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        pwdtxt.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        pwdtxt.setEchoChar('*');
    }//GEN-LAST:event_jLabel17MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WTLMS;
    private javax.swing.JLabel WTLMS1;
    private javax.swing.JLabel WTLMS2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelcancel;
    private javax.swing.JLabel jLabellogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwdtxt;
    private javax.swing.JTextField usrtxt;
    // End of variables declaration//GEN-END:variables
}
